"""
Saved-visualization tools for the Wazuh dashboard (OpenSearch Dashboards
saved-objects API).
"""
from __future__ import annotations

import json
from typing import Any

from tools.base import BaseWazuhTool, Permission, ToolContext, ToolError
from tools.dashboard.client import dashboards_request


def vis_state_json(title: str, vis_type: str, aggs: list[dict[str, Any]],
                   params: dict[str, Any] | None = None) -> str:
    """Serialize the visState JSON string OpenSearch Dashboards needs in a
    visualization's attributes. `aggs` are full agg JSON defs built by
    dashboard_engine."""
    return json.dumps({"title": title, "type": vis_type, "aggs": aggs,
                       "params": params or {}})


class GetWazuhVisualizations(BaseWazuhTool):
    name = "get_wazuh_visualizations"
    description = ("List saved visualizations on the Wazuh dashboard (saved-objects API) - "
                   "see what already exists before creating more.")
    input_schema = {
        "type": "object",
        "properties": {"limit": {"type": "integer", "description": "max results (default 20)"}},
        "required": [],
    }
    permission = Permission.READ

    def run(self, ctx: ToolContext, **params: Any) -> Any:
        p = self.validate(params)
        limit = min(int(p.get("limit", 20) or 20), 100)
        try:
            resp = dashboards_request(
                "GET", "/api/saved_objects/_find",
                params={"type": "visualization", "per_page": limit},
            )
        except ToolError:
            raise
        items = resp.get("saved_objects") or resp.get("objects") or []
        out = [{"id": i.get("id"), "title": (i.get("attributes") or {}).get("title")} for i in items]
        return {"count": len(out), "visualizations": out, "dashboard_ok": True}


class CreateWazuhVisualization(BaseWazuhTool):
    name = "create_wazuh_visualization"
    description = ("Create a saved visualization on the Wazuh dashboard from a validated "
                   "visState (type + aggs + params JSON string built by the dashboard engineer). "
                   "WRITE - proposes and requires human approval.")
    input_schema = {
        "type": "object",
        "properties": {
            "title": {"type": "string"},
            "vis_type": {"type": "string", "description": "metric | table | bar | line | area | pie"},
            "vis_state": {"type": "string", "description": "full visState JSON string"},
            "reason": {"type": "string"},
        },
        "required": ["title", "vis_type", "vis_state", "reason"],
    }
    permission = Permission.PROPOSE

    def run(self, ctx: ToolContext, **params: Any) -> Any:
        p = self.validate(params)
        try:
            json.loads(p["vis_state"])
        except json.JSONDecodeError as e:
            raise ToolError(f"vis_state is not valid JSON: {e}")
        proposed = {
            "action": "create_wazuh_visualization",
            "reason": p.get("reason", ""),
            "payload": {"title": p["title"], "vis_type": p["vis_type"], "vis_state": p["vis_state"]},
            "permission": self.permission.value,
        }
        proposed["generated_config"] = p["vis_state"]
        proposed["validation"] = {"valid": True, "note": "visState JSON is well-formed."}
        ctx.approve_or_raise(proposed)
        try:
            resp = dashboards_request(
                "POST", "/api/saved_objects/visualization",
                body={
                    "attributes": {
                        "title": p["title"],
                        "visState": p["vis_state"],
                        "description": "Generated by the AI SOC engineer (approved)",
                        "version": 1,
                    },
                    "references": [],
                },
            )
        except ToolError:
            raise
        resp_obj = resp.get("saved_object") or resp.get("object") or {}
        obj_id = resp_obj.get("id") or resp.get("id")
        return {"status": "executed", "visualization_id": obj_id, "title": p["title"],
                "detail": resp.get("message")}