"""
Wazuh connector (queries the Wazuh indexer / OpenSearch API).

Wazuh stores every alert in its indexer, so the most reliable way to pull
alerts is the OpenSearch `_search` API - the same protocol the Wazuh dashboard
and the official docs use. Endpoints:

  POST {host}/{index}/_search      (query alert documents)
  POST {host}/{index}/_update/{id} (annotate/close an alert)
  GET  {host}/                     (cluster info - health check)

Auth: HTTP Basic against the indexer's internal user (default `admin`/`admin`
for the docker deployment in wazuh/). The indexer serves self-signed
certificates generated by the deployment -> set verify_ssl=false or point
ca_cert at config/wazuh_indexer_ssl_certs/root-ca.pem.

Alerts are read from the configured index (default `wazuh-alerts-*`) and
mapped from Wazuh's document fields (rule.level, agent.name, data.srcip, ...).
"""
from __future__ import annotations
import requests
from typing import Any

from config import cfg
from connectors.siem.base import SIEMConnector, resolve_cfg, resolve_bool_cfg

DEFAULT_INDEX = "wazuh-alerts-*"
DEFAULT_RELATED_INDEX = "wazuh-archives-*"  # raw events, for correlation lookup
DEFAULT_QUERY_SIZE = 20


def _looks_local(host: str) -> bool:
    return any(marker in host for marker in ("localhost", "127.0.0.1", "0.0.0.0", "::1"))


def wazuh_severity(level: Any) -> str:
    """Map the Wazuh rule level (0-15) onto the common severity vocabulary."""
    try:
        level = int(level)
    except (TypeError, ValueError):
        return "unknown"
    if level >= 12:
        return "critical"
    if level >= 9:
        return "high"
    if level >= 6:
        return "medium"
    if level >= 3:
        return "low"
    return "info"


class WazuhConnector(SIEMConnector):
    platform = "wazuh"

    def __init__(self, name: str = "default", config: dict[str, Any] | None = None):
        super().__init__(name=name, config=config)
        self.host = resolve_cfg(config, "host", cfg.WAZUH_HOST).rstrip("/")
        self.username = resolve_cfg(config, "username", cfg.WAZUH_USERNAME) or "admin"
        self.password = resolve_cfg(config, "password", cfg.WAZUH_PASSWORD) or "admin"
        # The bundled wazuh/docker-compose.yml stack genuinely uses admin/admin
        # (self-signed, local-only) - that's a documented, intentional default.
        # It's a *silent* default credential the moment WAZUH_HOST points
        # somewhere that isn't local, so refuse to connect there without an
        # explicit password rather than quietly authenticating with admin/admin.
        if (
            not cfg.MOCK_MODE
            and self.password == "admin"
            and self.host
            and not _looks_local(self.host)
        ):
            raise ValueError(
                f"Wazuh host '{self.host}' isn't local, but no WAZUH_PASSWORD "
                "(or per-provider 'password') is set - refusing to connect with "
                "the default admin/admin credential. Set a real password, or "
                "explicitly pass password=admin if that's genuinely correct."
            )
        self.index = resolve_cfg(config, "index", cfg.WAZUH_INDEX) or DEFAULT_INDEX
        self.related_index = resolve_cfg(config, "related_index", cfg.WAZUH_RELATED_INDEX) or DEFAULT_RELATED_INDEX
        # Self-signed by default with these deployments; a ca_cert path wins.
        self.verify = (
            resolve_cfg(config, "ca_cert", cfg.WAZUH_CA_CERT)
            or resolve_bool_cfg(config, "verify_ssl", cfg.WAZUH_VERIFY_SSL)
        )
        self.auth = requests.auth.HTTPBasicAuth(self.username, self.password)

    # ------------------------------------------------------------------ #
    def _search(self, index: str, body: dict[str, Any]) -> list[dict[str, Any]]:
        r = requests.post(
            f"{self.host}/{index}/_search",
            auth=self.auth,
            json=body,
            verify=self.verify,
            timeout=20,
        )
        r.raise_for_status()
        return r.json().get("hits", {}).get("hits", [])

    # ------------------------------------------------------------------ #
    def get_new_alerts(self) -> list[dict[str, Any]]:
        hits = self._search(self.index, {
            "size": DEFAULT_QUERY_SIZE,
            "sort": [{"timestamp": {"order": "desc"}}],
            "query": {
                "bool": {
                    "must": [{"exists": {"field": "rule"}}],
                }
            },
        })
        return [self._normalize(h["_source"], h["_id"]) for h in hits]

    def search_related_events(
        self,
        host: str | None = None,
        user: str | None = None,
        earliest: str = "-24h",
        index: str = "*",
    ) -> list[dict[str, Any]]:
        """Correlation lookup against the archive (raw event) index."""
        index = self.related_index if index == "*" else index
        should: list[dict[str, Any]] = []
        if host:
            should.append({"term": {"agent.name": host}})
            should.append({"term": {"data.srcip": host}})
        if user:
            # Wazuh puts the user in different data.* fields depending on OS
            for field in ("data.user", "data.srcuser", "data.winuser", "data.linuxuser"):
                should.append({"term": {field: user}})
        query: dict[str, Any] = {
            "bool": {"filter": [{"range": {"timestamp": {"gte": "now-1d"}}}]},
        }
        if should:
            query["bool"]["should"] = should
            query["bool"]["minimum_should_match"] = 1
        hits = self._search(index, {
            "size": 50,
            "sort": [{"timestamp": {"order": "desc"}}],
            "query": query,
        })
        return [self._normalize(h["_source"], h["_id"]) for h in hits]

    def close_notable(self, event_id: str, status: str, comment: str) -> None:
        """Annotate the alert doc with the agent's verdict (rite-side note).

        Wazuh has no native 'close alert' endpoint on the indexer; this tags
        the document the same way the Elastic connector does. The manager
        re-writes alert docs on new data, so treat this as a note, not a
        source-of-truth status change.
        """
        r = requests.post(
            f"{self.host}/{self.index}/_update/{event_id}",
            auth=self.auth,
            json={"doc": {"soc_agent_status": status, "soc_agent_note": comment}},
            verify=self.verify,
            timeout=15,
        )
        r.raise_for_status()

    # ------------------------------------------------------------------ #
    def _ping(self) -> str:
        r = requests.get(self.host, auth=self.auth, verify=self.verify, timeout=10)
        r.raise_for_status()
        name = (r.json() or {}).get("cluster_name", "")
        return f"Wazuh indexer cluster {name} auth OK ({self.index})"

    @staticmethod
    def _normalize(src: dict[str, Any], doc_id: str) -> dict[str, Any]:
        rule = src.get("rule") or {}
        agent = src.get("agent") or {}
        data = src.get("data") or {}
        user = (
            data.get("user") or data.get("srcuser")
            or data.get("winuser") or data.get("linuxuser")
        )
        return {
            "alert_id": src.get("id") or doc_id,
            "rule_name": (rule.get("description") if isinstance(rule, dict) else None)
                or (rule.get("groups", [None])[0] if isinstance(rule, dict) else None)
                or "Wazuh alert",
            "severity": wazuh_severity(rule.get("level") if isinstance(rule, dict) else None),
            "description": src.get("full_log")
                or (rule.get("description") if isinstance(rule, dict) else None)
                or "",
            "host": (agent.get("name") if isinstance(agent, dict) else None),
            "user": user,
            "src_ip": data.get("srcip") or data.get("src_ip"),
            "raw_fields": src,
        }